In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
import os

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import (
    StandardScaler,
    LabelEncoder
)

from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [2]:

df = pd.read_csv("../data/insurance.csv")

In [3]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
median_value = df["charges"].median()

df["insurance_category"] = np.where(
    df["charges"] > median_value,
    1,
    0
)

In [5]:
df.drop("charges", axis=1, inplace=True)

In [6]:
le = LabelEncoder()

categorical_columns = df.select_dtypes(
    include=['object']
).columns

for col in categorical_columns:
    df[col] = le.fit_transform(df[col])

df.head()

   age  sex     bmi  children  smoker  region  insurance_category
0   19    0  27.900         0       1       3                   1
1   18    1  33.770         1       0       2                   0
2   28    1  33.000         3       0       2                   0
3   33    1  22.705         0       0       1                   1
4   32    1  28.880         0       0       1                   0

In [7]:
X = df.drop("insurance_category", axis=1)

y = df["insurance_category"]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [9]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [10]:
model = KNeighborsClassifier(
    n_neighbors=5
)

In [11]:
model.fit(X_train, y_train)

KNeighborsClassifier()

In [12]:
y_pred = model.predict(X_test)

In [13]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", accuracy)

print("\nClassification Report")

print(classification_report(y_test, y_pred))

print("\nConfusion Matrix")

print(confusion_matrix(y_test, y_pred))

Accuracy : 0.9067164179104478

Classification Report
              precision    recall  f1-score   support

           0       0.93      0.90      0.91       146
           1       0.88      0.92      0.90       122

    accuracy                           0.91       268
   macro avg       0.91      0.91      0.91       268
weighted avg       0.91      0.91      0.91       268


Confusion Matrix
[[131  15]
 [ 10 112]]

In [14]:
os.makedirs("../models", exist_ok=True)

pickle.dump(
    model,
    open("../models/knn_classifier.pkl", "wb")
)

pickle.dump(
    scaler,
    open("../models/scaler.pkl", "wb")
)

print("Model Saved Successfully")

Model Saved Successfully